version: "3.3"
services:
  v2ray:
    image: ghcr.io/antyung88/v2ray:main
    container_name: v2ray
    restart: always
    networks:
      - v2ray
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - 9000:9000 # Specify Port Number
